apiVersion: orgloop/v1alpha1
kind: TransformGroup

transforms:
  - name: drop-bot-noise
    type: package
    package: "@orgloop/transform-filter"
    config:
      exclude:
        provenance.author_type: bot
    timeout_ms: 5000

  - name: my-notifications
    description: "Keep events involving watched GitHub accounts (CSV env var)"
    type: package
    package: "@orgloop/transform-filter"
    config:
      match_any:
        provenance.pr_author: "${GITHUB_WATCHED}"
        provenance.author: "${GITHUB_WATCHED}"
    timeout_ms: 5000

  - name: dedup
    type: package
    package: "@orgloop/transform-dedup"
    config:
      window: "10m"
      fields:
        - "type"
        - "provenance.source"
        - "provenance.resource_id"
    timeout_ms: 5000
