apiVersion: orgloop/v1alpha1
kind: LoggerGroup

loggers:
  - name: file-log
    type: "@orgloop/logger-file"
    config:
      path: "~/.orgloop/logs/orgloop.log"
      format: jsonl
      rotation:
        max_size: "10MB"
        max_age: "7d"
        max_files: 5
