# Linear source — polls for ticket state changes and comments

apiVersion: orgloop/v1alpha1
kind: ConnectorGroup

sources:
  - id: linear
    description: Linear ticket state changes and comments
    connector: "@orgloop/connector-linear"
    config:
      team: "${LINEAR_TEAM_KEY}"
      api_key: "${LINEAR_API_KEY}"
    poll:
      interval: 5m
    emits:
      - resource.changed
