apiVersion: orgloop/v1alpha1
kind: Module
metadata:
  name: engineering
  description: "Engineering organization workflow — PR review, CI failure triage, Linear tickets, Claude Code supervision"
  version: 1.0.0

requires:
  connectors:
    - type: source
      id: github
      connector: "@orgloop/connector-github"
      required: true

    - type: source
      id: linear
      connector: "@orgloop/connector-linear"
      required: false
      fallback: skip

    - type: source
      id: claude-code
      connector: "@orgloop/connector-claude-code"
      required: false
      fallback: skip

    - type: actor
      id: agent
      connector: "@orgloop/connector-openclaw"
      required: true

  services:
    - name: openclaw
      detect:
        http: "http://127.0.0.1:18789/health"
      install:
        brew: "openclaw"
        docs: "https://docs.openclaw.dev/install"
      provides_credentials:
        - OPENCLAW_WEBHOOK_TOKEN

  credentials:
    - name: GITHUB_TOKEN
      description: "GitHub personal access token (repo scope)"
      required: true
      create_url: "https://github.com/settings/tokens/new?scopes=repo,read:org"

    - name: LINEAR_API_KEY
      description: "Linear API key"
      required: false

    - name: OPENCLAW_WEBHOOK_TOKEN
      description: "OpenClaw webhook authentication token"
      required: true

    - name: GITHUB_WATCHED
      description: "Comma-separated GitHub usernames to watch (your user + your bot)"
      required: true

parameters:
  - name: github_source
    description: "Name of your GitHub source connector"
    type: string
    required: true
    default: github

  - name: linear_source
    description: "Name of your Linear source connector"
    type: string
    required: false
    default: linear

  - name: claude_code_source
    description: "Name of your Claude Code source connector"
    type: string
    required: false
    default: claude-code

  - name: agent_actor
    description: "Name of your agent actor"
    type: string
    required: true
    default: openclaw-engineering-agent

provides:
  routes: 5
  transforms: 3
  sops: 4
